version: 1.0.{build}

image:
  - Ubuntu
  - macos

for:
  -
    matrix:
      only:
        - image: Ubuntu
    install:
      - sh: sudo apt-get install -y libcmocka-dev;
      - sh: git clone https://github.com/yonzkon/cio.git
      - sh: cd cio && mkdir build && cd build && cmake ..
      - sh: sudo make install
      - sh: cd ../../
    build: off
    build_script:
      - mkdir build && cd build
      - cmake .. -DBUILD_TESTS=on
      - make
    test_script:
      - make test
  -
    matrix:
      only:
        - image: macos
    install:
      - sh: export C_INCLUDE_PATH=/usr/local/include
      - sh: export LIBRARY_PATH=/usr/local/lib
      - sh: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmocka readline;
      - sh: git clone https://github.com/yonzkon/cio.git
      - sh: cd cio && mkdir build && cd build && cmake ..
      - sh: sudo make install
      - sh: cd ../../
      - sh: export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    build: off
    build_script:
      - mkdir build && cd build
      - cmake .. -DBUILD_TESTS=on
      - make
    test_script:
      - make test
