[package]
name = "srrp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srrp-sys = { path = "./libsrrp-sys", version = "0.1.0" }
log = "0.4"
cio = { git = "https://github.com/yonzkon/cio" }